<?php
	$p = params();
	
	initAdmin();
	
	$tempPath 	= "misc/pack/".time()."/";
	$zipname 	= time().".zip";
	makePath($tempPath);
	
	$exports = json_decode($p["export"], true);
	
	$copyBufferDirs 	= array();
	$copyBufferFiles 	= array();
	
	// copy files and folders
	foreach ($exports["files"] as $file) {
		$info = pathInfo($file);
		makePath($tempPath.$info["dirname"]);
		copy($file, $tempPath.$file);
		$cleanFile = str_replace($p["base"], "", $file);
		array_push($copyBufferFiles, array($cleanFile, $cleanFile));
	}
	foreach ($exports["dirs"] as $dir) {
		makePath($tempPath.$dir);
		copy_directory($dir, $tempPath.$dir);
		$cleanDir = str_replace($p["base"], "", $dir);
		array_push($copyBufferDirs, array($cleanDir, $cleanDir));
	}
	
	// create install.conf
	$installData = array(
		"meta"	=> array(
			"name"		=> $p["name"],
			"author"	=> $p["author"],
			"version"	=> $p["version"],
			"contact"	=> $p["email"],
			"website"	=> $p["website"],
			"contributors"	=> array(
				"Pack Generator"	=> array("Likiweb App Manager v0.6")
			)
		),
		"copy"	=> array(
			"directories"	=> $copyBufferDirs,
			"files"			=> $copyBufferFiles
		),
		"installScript"	=> false
	);
	file_put_contents($tempPath."install.conf", json_encode($installData));
	
	// zip archive
	$createZipFile 	= new Zip(true);  //
	$createZipFile->setZipFile($tempPath.$zipname);
	$createZipFile->setComment("".$p["name"]." version ".$p["version"]."\nGenerated by Likiweb App Manager\nCreated on " . date('l jS \of F Y h:i:s A'));
	
	// list files
	$__files 		= getFileAsArray($tempPath);
	$__dirs 		= getDirAsArray($tempPath, array("..","."));
	foreach ($__dirs as $dir) {
		$createZipFile->addDirectoryContent($tempPath.$dir, $dir);
	}
	foreach ($__files as $file) {
		if ($file != $zipname) {
			$createZipFile->addFile(file_get_contents($tempPath.$file),$file);
		}
	}
	$createZipFile->finalize();
	
	echo $tempPath.$zipname;
?>